/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_rutgers_winlab_jgnrs_JGNRS */

#ifndef _Included_edu_rutgers_winlab_jgnrs_JGNRS
#define _Included_edu_rutgers_winlab_jgnrs_JGNRS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_rutgers_winlab_jgnrs_JGNRS
 * Method:    setNativeGNRS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_rutgers_winlab_jgnrs_JGNRS_setNativeGNRS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_rutgers_winlab_jgnrs_JGNRS
 * Method:    freeNativeGNRS
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_rutgers_winlab_jgnrs_JGNRS_freeNativeGNRS
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_rutgers_winlab_jgnrs_JGNRS
 * Method:    setNativeGUID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_rutgers_winlab_jgnrs_JGNRS_setNativeGUID
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_rutgers_winlab_jgnrs_JGNRS
 * Method:    freeNativeGUID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_rutgers_winlab_jgnrs_JGNRS_freeNativeGUID
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_rutgers_winlab_jgnrs_JGNRS
 * Method:    gnrs_lookup
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_rutgers_winlab_jgnrs_JGNRS_gnrs_1lookup
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_rutgers_winlab_jgnrs_JGNRS
 * Method:    gnrs_add
 * Signature: (II[II)I
 */
JNIEXPORT jint JNICALL Java_edu_rutgers_winlab_jgnrs_JGNRS_gnrs_1add
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
