# This file was automatically generated by oml2-scaffold V2.10.0
# The syntax of this file is documented at [0].
#
# [0] http://doc.mytestbed.net/doc/omf/OmfEc/Backward/AppDefinition.html

defApplication('wontoniii:app:mfstack', 'mfstack') do |app|

  app.version(1, 0, 0)
  app.shortDescription = 'MobilityFirst network protocol host stack'
  app.description = %{
  MobilityFirst stack used in prototype testing
}
  app.path = "/root/bin/mfstack"

  # Declare command-line arguments; generate Popt parser with
  #  oml2-scaffold --opts mfandroidstack.rb

  # Example of a command-line argument types; see popt(3) for more details
  #  app.defProperty('double_var', 'Command line option of type double', '--double',
  #        :type => :double, :var_name => 'vardouble')


  # Declare measurement points; generate OML injection helpers with
  #  oml2-scaffold --oml mfandroidstack.rb
  app.defMeasurement("interface_statistics") do |mp|
	  mp.defMetric('interface_ID', :uint32)
	  mp.defMetric('ifname', :string)
	  mp.defMetric('mac', :string)
  	mp.defMetric('inpackets', :uint32)
  	mp.defMetric('outpackets', :uint32)
  	mp.defMetric('inbytes', :uint32)
  	mp.defMetric('outbytes', :uint32)
  end
  
  app.defMeasurement("chunks_statistics") do |mp|
	  mp.defMetric('defaultGUID', :blob)
	  mp.defMetric('inchunks', :uint32)
	  mp.defMetric('outchunks', :uint32)
  end

end

# Local Variables:
# mode:ruby
# End:
# vim: ft=ruby:sw=2
