CC=gcc
CFLAGS=-c -Wall -I$(MF_HOME)/common/ -I$(MF_HOME)/mfclient/netapi/c/src/ -DLINUX
LDFLAGS=-lmfapi -lpthread -lm
SOURCES=ping.c
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=mfping

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.c.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *.o $(EXECUTABLE)
